<a href="https://colab.research.google.com/github/khushishetty/Internship/blob/master/Beginning_with_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
3*1
5*1+6


11

In [0]:
10/5

2.0

In [0]:
15*20

300

In [0]:
2^^4

SyntaxError: ignored

In [0]:
2**4


16

In [0]:
(2*5)+(9*2)

28

In [0]:
x=2
y=30
z=x+y
print(z)

32


In [0]:
print("The value of z is ",z)

The value of z is  32


In [0]:
z


32

In [0]:
x=[1,2,3]
print(x)

[1, 2, 3]


In [0]:
x[1]

2

In [0]:
list_1=['hello all',[1,2,3],4,5]
print(list_1)

['hello all', [1, 2, 3], 4, 5]


In [0]:
list_1.append('karnataka')
print(list_1)


['hello all', [1, 2, 3], 4, 5, 'karnataka']


In [0]:
print(list_1[2:4])

[4, 5]


In [0]:
list_1[2]='khushi'

In [0]:
print(list_1)

['hello all', [1, 2, 3], 'khushi', 5, 'karnataka']


In [0]:
x,y=10,20
print(x "and" y)

SyntaxError: ignored

In [0]:
print(x,"and",y)


[1, 2, 3] and 30


In [0]:
x,y=10,20
print(x)
print(y)

10
20


In [0]:
x,y=y,x
print(x)
print(y)

20
10


In [0]:
college="VTU is a cool university"
print(college)

VTU is a cool university


In [0]:
print("reverse is ",college[::-1])

reverse is  ytisrevinu looc a si UTV


In [0]:
print(college[2:4:0])

ValueError: ignored

In [0]:
college[2:10:3]

'Us '

In [0]:
import os
import socket
print(os)

<module 'os' from '/usr/lib/python3.6/os.py'>


In [0]:
def funcn():                    '''function definition'''
  print("This is my function")

funcn()

IndentationError: ignored

In [0]:
def square(x):
  print("Area is : ",x*x)
square(10)

Area is :  100


In [0]:
def multi():
  return 1,2,3,4
a,b,c,d=multi()
print(a,b,c,d)

1 2 3 4


In [0]:
kat=32
if kat is 30:
  print("hey")
else:
  print("bye")

bye


In [0]:
import sys
print(sys.getsizeof(kat))

28


In [0]:
original=[['a','b'],['c','d'],['e','f']]
transpose=zip(*original)
print(list(transpose))

[('a', 'c', 'e'), ('b', 'd', 'f')]


In [0]:
6<7

True

In [0]:
b=6
print(15<b<17)

False


In [0]:
if (2==2):
  print("correct")
else:
  print("Incorrect")

correct


In [0]:
def mul(a,b):
  return(a*b)

def addd(a,b):
  return(a+b)
b=False
print((mul if b else addd)(5,7))

12


In [0]:

a=b
b=[30,40]
a

[30, 40]

In [0]:
b[0]='khushi'

In [0]:
a


[30, 40]

In [0]:
art=[1,23,3,4,5]
print(list(art))

[1, 23, 3, 4, 5]


In [0]:
print(art.copy())

[1, 23, 3, 4, 5]


In [0]:
from copy import deepcopy
mat=[[1,2],[3,4]]
kat_2=deepcopy(mat)
print(kat_2)

[[1, 2], [3, 4]]


In [0]:
for i in range(0,11,2):
  print(i)

0
2
4
6
8
10


In [0]:
even_1=[i for i in range(11) if i%2==0]
print(even_1)

[0, 2, 4, 6, 8, 10]


In [0]:
odd_1=[i for i in range(2,11) if i%2!=0]
print(odd_1)

[3, 5, 7, 9]


In [0]:
print(dir(list))


['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [0]:
even_1.append(60)
print(even_1)

[0, 2, 4, 6, 8, 10, 60]


In [0]:
print(even_1.count)

<built-in method count of list object at 0x7f65a81d7988>


In [0]:
even_1.insert(27,2)
print(even_1)

[0, 2, 4, 6, 8, 10, 60, 2]


In [0]:
print(help(list.append))

Help on method_descriptor:

append(...)
    L.append(object) -> None -- append object to end

None


In [0]:
print(help(list.count))

Help on method_descriptor:

count(...)
    L.count(value) -> integer -- return number of occurrences of value

None


In [0]:
dic_1={'a':1,'b':2,'c':3}
for key,value in dic_1.items():
  print(" {} : {} ".format(key,value))

 a : 1 
 b : 2 
 c : 3 


In [0]:
dict_1={i : i**2 for i in range(0,11)}
print(dict_1)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [0]:
arr=[1,1,1,2,3,3,3,3,5,5,6]
print(set(arr))

{1, 2, 3, 5, 6}


In [0]:
print(list(set(arr)))

[1, 2, 3, 5, 6]


In [0]:
x,*y,z=2,4,6,8
x


2

In [0]:
y

[4, 6]

In [0]:
z

8

In [0]:
x={'u':1}

In [0]:
print(x)

{'u': 1}


In [0]:
y={'v':2}
print(y)

{'v': 2}


In [0]:
z={**x,**y,'q':3}

In [0]:
z

{'q': 3, 'u': 1, 'v': 2}

In [0]:
x={'u':4,'w':2,'v':1}
sorted(x.items())

[('u', 4), ('v', 1), ('w', 2)]

In [0]:
sorted(x.items(),key=lambda item:item[1])

[('v', 1), ('w', 2), ('u', 4)]

In [0]:
students=["khushi","iral","nidhi"]

In [0]:
marks=[10,0,120]
d=dict(zip(students,marks))
d

{'iral': 0, 'khushi': 10, 'nidhi': 120}

In [0]:
sorted(d.items())


[('iral', 0), ('khushi', 10), ('nidhi', 120)]

In [0]:
sorted(d.items(),key=lambda item:item[1])

[('iral', 0), ('khushi', 10), ('nidhi', 120)]

In [0]:
import time
t1=time.clock()

In [0]:
print(t1)

4.692791


In [0]:
!pip install emoji

     |████████████████████████████████| 51kB 1.6MB/s 
  Created wheel for emoji: filename=emoji-0.5.4-cp36-none-any.whl size=42176 sha256=2414accad85dd91d817309773c4f464e7359479c5cb763d8bc74cd8c567a822e
  Stored in directory: /root/.cache/pip/wheels/2a/a9/0a/4f8e8cce8074232aba240caca3fade315bb49fac68808d1a9c
Successfully built emoji


In [0]:
from emoji import emojize
print(emojize(":thumbs_up:"))

👍


In [0]:
!pip install geopy
!pip install geopandas

In [0]:
'''from geopy import GoogleV3
place="Fort ,Mumbai"
location=GoogleV3().geocode(place)'''

x=[1,2,3]
y=map(lambda x:x+1,x)
print(list(y))

[2, 3, 4]


In [0]:
import random
print("Number Guessing game")
number=random.randint(0,10)
chances=0
print("please enter a number between 1 and 9")
guess=input()
while chances<2:
  if guess==number:
    print("Winner winner chicken dinner")
    exit()
  elif guess>number :
    print("your guess is high")
  else:
    print("Your guess is low")
  chances=chances+1
  if not chances <2:
   print("you lost as the betting number is",number)
   exit


Number Guessing game
please enter a number between 1 and 9
2


TypeError: ignored

In [0]:
import random

print("Number Guessing as a game")
### this variable is tracking chances
chances=0

number=random.randint(1,9)
print("Please Guess a number in between 1 and 9")

while chances<5:
  guess=int(input("enter a number"))

  if guess==number:

    print("Congrats you have won !!")
    break
  
  elif guess<number:
    print("Your guess is bit low")

  else:
    print("your guess is too high")


  chances+=1

if not chances <5:
  print("you lost as the betting number is",number)

Number Guessing as a game
Please Guess a number in between 1 and 9
enter a number1
Your guess is bit low
enter a number5
Your guess is bit low
enter a number7
your guess is too high
enter a number6
Congrats you have won !!


In [0]:
import numpy as np
array=([1,2,3])
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
kmat=np.zeros(5)
print(kmat)

[0. 0. 0. 0. 0.]


In [0]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(3)

array([1., 1., 1.])

In [0]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.random.rand(0,2)

array([], shape=(0, 2), dtype=float64)

In [0]:
np.random.randint(10)

0

In [0]:
np.random.randint(1,11,10)

array([10,  6,  2,  6, 10,  4,  5,  8,  1,  1])

In [0]:
arr=np.arange(3)

In [0]:
arr

array([0, 1, 2])

In [0]:
arr=np.random.randint(0,10,25)
print(arr)
arr.reshape(5,5)

[6 8 4 2 9 2 8 2 4 0 2 3 6 7 1 4 1 7 5 7 4 4 4 3 5]


array([[6, 8, 4, 2, 9],
       [2, 8, 2, 4, 0],
       [2, 3, 6, 7, 1],
       [4, 1, 7, 5, 7],
       [4, 4, 4, 3, 5]])

In [0]:
arr.argmax()

4

In [0]:
arr.reshape(1,25)

array([[6, 8, 4, 2, 9, 2, 8, 2, 4, 0, 2, 3, 6, 7, 1, 4, 1, 7, 5, 7, 4, 4,
        4, 3, 5]])

In [0]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([1.79175947, 2.07944154, 1.38629436, 0.69314718, 2.19722458,
       0.69314718, 2.07944154, 0.69314718, 1.38629436,       -inf,
       0.69314718, 1.09861229, 1.79175947, 1.94591015, 0.        ,
       1.38629436, 0.        , 1.94591015, 1.60943791, 1.94591015,
       1.38629436, 1.38629436, 1.38629436, 1.09861229, 1.60943791])

In [0]:
slice_of_arr=arr[0:6]

In [0]:
slice_of_arr

array([6, 8, 4, 2, 9, 2])

In [0]:
arr[:]=99

In [0]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99])

In [0]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99])

In [0]:
!ls

sample_data


In [0]:
!git clone https://github.com/aniforverizon/nitte_data

Cloning into 'nitte_data'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.


In [0]:
!ls

nitte_data  sample_data


In [0]:
import numpy as np
import pandas as pd
labels=['a','b','k']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [0]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [0]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [0]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [0]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [0]:
d

{'a': 10, 'b': 20, 'c': 30}

In [0]:
pd.Series(data=d,index=labels)

a    10
b    20
c    30
dtype: int64

In [0]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [0]:
ser_1=pd.Series(data=[1,2,3,4],index=['usa',"india","china","japan"])

In [0]:
ser_2=pd.Series(data=[1,2,3,4],index=['usa',"india","italy","Singapore"])
ser_2

usa          1
india        2
italy        3
Singapore    4
dtype: int64

In [0]:
ser_2[3]

4

In [0]:
ser_1+ser_2

Singapore    NaN
china        NaN
india        4.0
italy        NaN
japan        NaN
usa          2.0
dtype: float64

In [0]:
from numpy.random import randn
df=pd.DataFrame(randn(5,4),index='a b c d e'.split(),columns='w x y z'.split())

np.random.seed(101)
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df[['w','z']]

w         z
a  2.706850  0.503826
b  0.651118  0.605965
c -2.018168 -0.589001
d  0.188695  0.955057
e  0.190794  0.683509

In [0]:
type(df['w'])

pandas.core.series.Series

In [0]:
df['new']=df['w']+df['x']
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.334983
b  0.651118 -0.319318 -0.848077  0.605965  0.331800
c -2.018168  0.740122  0.528813 -0.589001 -1.278046
d  0.188695 -0.758872 -0.933237  0.955057 -0.570177
e  0.190794  1.978757  2.605967  0.683509  2.169552

In [0]:
df.drop('new',axis=1,inplace=True)

In [0]:
df.drop('e',axis=0)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

In [0]:
df.iloc[2]

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: c, dtype: float64

In [0]:
df.loc['b','y']

-0.8480769834036315

In [0]:
df.loc[['a','b'],['x','y']]

x         y
a  0.628133  0.907969
b -0.319318 -0.848077

0

TypeError: ignored

In [0]:
new_index=df
new_index

0

# New Section

In [0]:
from numpy.random import randn
df=pd.DataFrame(randn(5,4),index='a b c d e'.split(),columns='w x y z'.split())

np.random.seed(101)
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
new_index=df

In [0]:
df=pd.DataFrame({
    'A':[1,2,np.nan],
    'B':[1,np.nan,np.nan],
    'C':[7,8,9]
})

In [0]:
df

A    B  C
0  1.0  1.0  7
1  2.0  NaN  8
2  NaN  NaN  9

In [0]:
df.dropna()

A    B  C
0  1.0  1.0  7

In [0]:
df.dropna(axis=1)

C
0  7
1  8
2  9

In [0]:
df.fillna(value="Empty")

A      B  C
0      1      1  7
1      2  Empty  8
2  Empty  Empty  9

In [0]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [0]:
##requests
import requests
url="https://images.newindianexpress.com/uploads/user/imagelibrary/2020/3/5/w1200X800/MS_Dhoni_AP.jpg"
result=requests.get(url)
result.status_code

200

In [0]:
result

<Response [200]>

In [0]:
file=open("Dhoni.jpg","wb")
file.write(result.content)

83853

In [0]:
file.close()

In [0]:
import os
url="https://graph.facebook.com/{}/image?type=large"
if not "fb_displaypics" in os.listdir():
  os.mkdir("fb_displaypics")
for i in range(4,20):
  result=requests.get(url.format(i))
  with open("fb_displaypics/{}_img.jpg".format(i),"wb")as file:
   file.write(result.content)


In [0]:
import pandas as pd
df=pd.DataFrame({'col1':[1,2,3,4],
                 'col2':[444,555,666,777],
                 'col3':['hey','hello','khushi','jaya']
                 }) 
df

col1  col2    col3
0     1   444     hey
1     2   555   hello
2     3   666  khushi
3     4   777    jaya

In [0]:
del df["col1"]

In [0]:
df

col2    col3
0   444     hey
1   555   hello
2   666  khushi
3   777    jaya

In [0]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [0]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
df.sort_values(by="col2")

col2    col3
0   444     hey
1   555   hello
2   666  khushi
3   777    jaya

In [0]:
df.sort_values(by="col3")

col2    col3
1   555   hello
0   444     hey
3   777    jaya
2   666  khushi

In [0]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [0]:
df.dropna()

col2    col3
0   444     hey
1   555   hello
2   666  khushi
3   777    jaya

In [0]:
data={
    'A':["foo","foo","foo","bar","bar","bar"],
    'B':['one','one','two','two','one','one'],
    'C':['x','y','x','y','x','y'],
    'D':[1,3,2,5,4,1]
}
df=pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [0]:
df.pivot_table()

In [0]:
data ={'Company':['GOOGLE','GOOGLE','GOOGLE',
                  'MICROSOFT','MICROSOFT',"FB","FB"],
       'Person':['Prajna','Ajay','Sridhar sir','prajwal','sahdev',
       'Aravind','Anubhav'],
       'Sales':[200,120,340,124,243,350,560]
    

}

df_1=pd.DataFrame(data)


In [0]:
df_1

Company       Person  Sales
0     GOOGLE       Prajna    200
1     GOOGLE         Ajay    120
2     GOOGLE  Sridhar sir    340
3  MICROSOFT      prajwal    124
4  MICROSOFT       sahdev    243
5         FB      Aravind    350
6         FB      Anubhav    560